apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eventhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do sleep 2; done']
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo-service 27017; do sleep 2; done']
      containers:
        - name: backend
          image: mkxime/eventhub-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: eventhub-secrets
          env:
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: eventhub
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000