services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventhub
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db  

volumes:
  pgdata:
  mongo_data: